services:
  db:
    image: mysql:8.0
    volumes:
      - "./.db:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=payflow
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 10s
      retries: 5
